site_name: Roleplay Wettenbundel
site_url: https://wetten.roleplayneder.land/
site_description: 'Roleplay Wettenbundel'
site_author: 'RoleplayNL'

copyright: Copyright &copy; 2022-2023 RoleplayNL

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  language: nl
markdown_extensions:
  - toc:
      permalink: "#"
extra_javascript:
  - javascripts/headercopy.js
nav:
  - Home: 'index.md'
  - Wetboek van Strafvordering: 'wetboek-van-strafvordering.md'
  - Wetboek van Strafrecht: 'wetboek-van-strafrecht.md'
  - Wegenverkeers wetgeving:
    - Wegenverkeerswet 1994: 'wegenverkeerswet/wegenverkeerswet-1994.md'
    - Wet Mulder: 'wegenverkeerswet/wet-mulder.md'
    - RVV 1990: 'wegenverkeerswet/rvv-1990.md'
    - Feitenboekje: 'wegenverkeerswet/feitenboekje.md'
  - Vreemdelingenrecht:
    - Vreemdelingenwet 2000: 'vreemdelingenrecht/vreemdelingenwet.md'
    - Vreemdelingenbesluit 2000: 'vreemdelingenrecht/vreemdelingenbesluit.md'
  - Wet Wapens en Munitie: 'wet-wapens-en-munitie.md'
  - Opiumwet: 'opiumwet.md'
  - Politiewet 2012: 'politiewet-2012.md'
  - Ambtsinstructie: 'ambtsinstructie.md'
  - Wet op de identificatieplicht: 'wet-op-de-identificatieplicht.md'
  - Paspoortwet: 'paspoortwet.md'
  - Algemene wet op het binnentreden: 'algemene-wet-op-het-binnentreden.md'
  - Wet gedeeltelijk verbod gezichtsbedekkende kleding: 'wet-gedeeltelijk-verbod-gezichtsbedekkende-kleding.md'