site_name: 'Gemeente Future Wettenbundel'
site_url: https://wetten.roleplayneder.land/
site_description: 'Gemeente Future Wettenbundel'
site_author: 'that.edward'

copyright: 'Copyright &copy; 2022-2023 FutureRP | Alle rechten voorbehouden'

extra:
  generator: false
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  language: nl
markdown_extensions:
  - toc:
      permalink: "#"
extra_javascript:
  - javascripts/headercopy.js
nav:
  - Home: 'index.md'
  - APV Future: 'algemene-plaatselijke-verordening.md'
  - Wetboek van Strafvordering: 'wetboek-van-strafvordering.md'
  - Wetboek van Strafrecht: 'wetboek-van-strafrecht.md'
  - Wet Wapens en Munitie: 'wet-wapens-en-munitie.md'
  - Opiumwet: 'opiumwet.md'
  - Algemene Douanewet: 'algemene-douanewet.md'
  - Wegenverkeers wetgeving:
    - Wegenverkeerswet 1994: 'wegenverkeerswet/wegenverkeerswet-1994.md'
    - Wet Mulder: 'wegenverkeerswet/wet-mulder.md'
    - RVV 1990: 'wegenverkeerswet/rvv-1990.md'
    - Regeling maatregelen rijvaardigheid en geschiktheid: 'wegenverkeerswet/regeling-maatregelen-rijvaardigheid-en-geschiktheid.md'
    - Reglement rijbewijzen: 'wegenverkeerswet/reglement-rijbewijzen.md'
    - Reglement voertuigen: 'wegenverkeerswet/reglement-voertuigen.md'
    - Besluit voertuigen: 'wegenverkeerswet/besluit-voertuigen.md'
  - Politiewetten:
    - Politiewet 2012: 'politiewet-2012.md'
    - Ambtsinstructie: 'ambtsinstructie.md'
  - Overig:
    - Algemene wet bestuursrecht: 'algemene-wet-bestuursrecht.md'
    - Wet op de identificatieplicht: 'wet-op-de-identificatieplicht.md'
    - Paspoortwet: 'paspoortwet.md'
    - Algemene wet op het binnentreden: 'algemene-wet-op-het-binnentreden.md'
    - Wet gedeeltelijk verbod gezichtsbedekkende kleding: 'wet-gedeeltelijk-verbod-gezichtsbedekkende-kleding.md'
  - Strafvorderingsrichtlijnen: 'strafvorderingsrichtlijnen.md'
  - Beleidsregels: 'beleidsregels.md'
  - Kamer van Koophandel:
    - Regeling inzake de bedrijfsvoering: 'kvk-bedrijfsvoering.md'
